Repository party-time-2/party-time, pull requests merged in 2023-07, with the labels that each got.

#71 Eventfunktionalitaet veranstalter
  apps/party-time-backend/src/main/java/com/partytime/api/controller/EventController.java
  apps/party-time-backend/src/main/java/com/partytime/api/dto/event/EventDTO.java
  apps/party-time-backend/src/main/java/com/partytime/jpa/mapper/EventMapper.java
  apps/party-time-backend/src/main/java/com/partytime/jpa/mapper/EventParticipantMapper.java
  apps/party-time-backend/src/main/java/com/partytime/jpa/repository/EventParticipantRepository.java
  apps/party-time-backend/src/main/java/com/partytime/mail/MailService.java
  apps/party-time-backend/src/main/java/com/partytime/mail/model/invite/InvitationData.java
  apps/party-time-backend/src/main/java/com/partytime/service/AccountDeletionService.java
  apps/party-time-backend/src/main/java/com/partytime/service/EventService.java
  apps/party-time-backend/src/main/resources/application.yml
  apps/party-time-backend/src/main/resources/mail/invitation.mustache
  apps/party-time-frontend-e2e/src/e2e/create.event.cy.ts
  apps/party-time-frontend-e2e/src/e2e/participants.cy.ts
  apps/party-time-frontend-e2e/src/support/app.po.ts
  docs/F004/F004_gaesteEinladen_act.plantuml
  docs/F004/F004_gaesteEinladen_seq.plantuml
  docs/F005/F005_gaesteAusladen_act.plantuml
  docs/F005/F005_gaesteAusladen_seq.plantuml
  docs/F006/F006_teilnehmerUeberblicken_act.plantuml
  docs/F006/F006_teilnehmerUeberblicken_seq.plantuml
  docs/PNG/F004/F004_gaesteEinladen_act.png
  docs/PNG/F004/F004_gaesteEinladen_seq.png
  docs/PNG/F004/Tests/party-time-add-participant -- should show participant_already_invited.png
  docs/PNG/F004/Tests/party-time-add-participant -- should show participant_email_invalid.png
  docs/PNG/F004/Tests/party-time-add-participant -- should show participant_invite.png
  docs/PNG/F004/Tests/party-time-add-participant -- should show participant_unknown.png
  docs/PNG/F005/F005_gaesteAusladen_act.png
  docs/PNG/F005/F005_gaesteAusladen_seq.png
  docs/PNG/F005/Tests/party-time-remove-participant -- should show participant_not_invited_error.png
  docs/PNG/F005/Tests/party-time-remove-participant -- should show participant_remove.png
  docs/PNG/F006/F006_teilnehmerUeberblicken_act.png
  docs/PNG/F006/F006_teilnehmerUeberblicken_seq.png
  docs/PNG/F006/Tests/party-time-view-participants -- should show view_participants.png
  libs/event/README.md
  libs/event/src/lib/create/create-event.component.html
  libs/event/src/lib/create/create-event.component.ts
  libs/event/src/lib/lib.routes.ts
  libs/event/src/lib/overview/overview.component.html
  libs/event/src/lib/overview/overview.component.ts
  libs/event/src/lib/participants/+state/participants.state.ts
  libs/event/src/lib/participants/participants.component.html
  libs/event/src/lib/participants/participants.component.ts
  libs/event/src/lib/pipes/enum-to-participant-status.pipe.ts
  libs/event/src/lib/selector/selector.component.ts
  libs/event/src/lib/selectors/event-selector.component.ts
  libs/event/src/lib/selectors/participant-selector.component.ts
  libs/event/src/lib/services/event.service.ts
  libs/models/src/index.ts
  libs/models/src/lib/api/event.model.ts
  libs/models/src/lib/api/participant.model.ts
Labels: documentation, enhancement

#79 Bugfixes and todos lucas
  apps/party-time-backend/src/main/java/com/partytime/api/controller/EventController.java
  apps/party-time-backend/src/main/java/com/partytime/mail/MailService.java
  apps/party-time-backend/src/main/java/com/partytime/mail/model/univite/invite/UninviteData.java
  apps/party-time-backend/src/main/java/com/partytime/service/EventService.java
  apps/party-time-backend/src/main/resources/mail/uninvite.mustache
Labels: bug

#80 Ms event invited user
  apps/party-time-backend/src/main/java/com/partytime/api/controller/EventController.java
  apps/party-time-backend/src/main/java/com/partytime/api/controller/EventParticipantController.java
  apps/party-time-backend/src/main/java/com/partytime/api/dto/event/ParticipatingEventDTO.java
  apps/party-time-backend/src/main/java/com/partytime/configuration/JacksonConfiguration.java
  apps/party-time-backend/src/main/java/com/partytime/jpa/mapper/AddressMapper.java
  apps/party-time-backend/src/main/java/com/partytime/jpa/mapper/EventMapper.java
  apps/party-time-backend/src/main/java/com/partytime/jpa/repository/EventParticipantRepository.java
  apps/party-time-backend/src/main/java/com/partytime/jpa/repository/EventRepository.java
  apps/party-time-backend/src/main/java/com/partytime/mail/model/invite/InvitationData.java
  apps/party-time-backend/src/main/java/com/partytime/service/EventService.java
  apps/party-time-backend/src/main/resources/mail/invitation.mustache
  apps/party-time-frontend-e2e/src/e2e/invitation.cy.ts
  apps/party-time-frontend-e2e/src/support/app.po.ts
  apps/party-time-frontend/src/app/app.routes.ts
  docs/F007/F007_einladungErhalten_act.plantuml
  docs/F007/F007_einladungErhalten_seq.plantuml
  docs/F008/F008_zusageZumEventGeben_act.plantuml
  docs/F008/F008_zusageZumEventGeben_seq.plantuml
  docs/F009/F009_absageZumEventGeben_act.plantuml
  docs/F009/F009_absageZumEventGeben_seq.plantuml
  docs/PNG/F007/F007_einladungErhalten_act.png
  docs/PNG/F007/F007_einladungErhalten_seq.png
  docs/PNG/F008/F008_zusageZumEventGeben_act.png
  docs/PNG/F008/F008_zusageZumEventGeben_seq.png
  docs/PNG/F008/Tests/accept-invite success -- should show invite_accepted.png
  docs/PNG/F008/Tests/accet-invite error -- should show event_not_found.png
  docs/PNG/F008/Tests/accet-invite error -- should show participant_not_invited.png
  docs/PNG/F009/F009_absageZumEventGeben_act.png
  docs/PNG/F009/F009_absageZumEventGeben_seq.png
  docs/PNG/F009/Tests/decline-invite error -- should show event_not_found.png
  docs/PNG/F009/Tests/decline-invite error -- should show participant_not_invited.png
  docs/PNG/F009/Tests/decline-invite success -- should show invite_declined.png
  libs/event/src/lib/edit/edit-event.component.html
  libs/event/src/lib/edit/edit-event.component.ts
  libs/invitation/.eslintrc.json
  libs/invitation/README.md
  libs/invitation/jest.config.ts
  libs/invitation/project.json
  libs/invitation/src/index.ts
  libs/invitation/src/lib/+state/invitation.state.ts
  libs/invitation/src/lib/invitation/invitation.component.html
  libs/invitation/src/lib/invitation/invitation.component.ts
  libs/invitation/src/lib/lib.routes.ts
  libs/invitation/src/lib/services/invitation.service.ts
  libs/invitation/src/test-setup.ts
  libs/invitation/tsconfig.json
  libs/invitation/tsconfig.lib.json
  libs/invitation/tsconfig.spec.json
  libs/models/src/lib/api/event.model.ts
  tsconfig.base.json
Labels: enhancement

#70 designentscheidung account delete
  apps/party-time-backend/src/main/java/com/partytime/api/dto/address/AddressDTO.java
  apps/party-time-backend/src/main/java/com/partytime/api/dto/event/EventCreateDTO.java
  apps/party-time-backend/src/main/java/com/partytime/api/dto/event/EventDTO.java
  apps/party-time-backend/src/main/java/com/partytime/jpa/entity/Address.java
  apps/party-time-backend/src/main/java/com/partytime/jpa/entity/Event.java
  docs/Design-Entscheidungen/design-entscheidungen.md
Labels: documentation

#85 add design entscheidung
  docs/Design-Entscheidungen/design-entscheidungen.md
Labels: documentation

#87 Ms event teilnehmer funktionen
  apps/party-time-backend/src/main/java/com/partytime/mail/MailService.java
  apps/party-time-backend/src/main/java/com/partytime/mail/model/ics/IcsEventData.java
  apps/party-time-backend/src/main/java/com/partytime/mail/model/univite/UninviteData.java
  apps/party-time-backend/src/main/java/com/partytime/service/EventService.java
  apps/party-time-backend/src/main/resources/mail/change-event.mustache
  apps/party-time-backend/src/main/resources/mail/delete-event.mustache
  apps/party-time-backend/src/main/resources/mail/event-ics.mustache
  apps/party-time-frontend-e2e/src/e2e/location.cy.ts
  apps/party-time-frontend-e2e/src/support/app.po.ts
  docs/F017/F017_BenachrichtigungenZumEvent_act.plantuml
  docs/F017/F017_BenachrichtigungenZumEvent_seq.plantuml
  docs/F018/F018_WegbeschreibungZumEvent_act.plantuml
  docs/F018/F018_WegbeschreibungZumEvent_seq.plantuml
  docs/F019/F019_KalendereintragExportieren_act.plantuml
  docs/F019/F019_KalendereintragExportieren_seq.plantuml
  docs/PNG/F017/F017_BenachrichtigungenZumEvent_act.png
  docs/PNG/F017/F017_BenachrichtigungenZumEvent_seq.png
  docs/PNG/F018/F018_WegbeschreibungZumEvent_act.png
  docs/PNG/F018/F018_WegbeschreibungZumEvent_seq.png
  docs/PNG/F018/Tests/event-location error -- should show event_not_found.png
  docs/PNG/F018/Tests/event-location success -- should show map.png
  docs/PNG/F019/F019_KalendereintragExportieren_act.png
  docs/PNG/F019/F019_KalendereintragExportieren_seq.png
  libs/auth/src/lib/services/interceptor.service.ts
  libs/event/README.md
  libs/event/src/lib/event/event.component.ts
  libs/event/src/lib/lib.routes.ts
  libs/event/src/lib/location/+state/location.state.ts
  libs/event/src/lib/location/location.component.html
  libs/event/src/lib/location/location.component.ts
  libs/event/src/lib/other/+state/other.state.ts
  libs/event/src/lib/other/other.component.html
  libs/event/src/lib/other/other.component.ts
  libs/event/src/lib/pipes/safe.pipe.ts
  libs/event/src/lib/selectors/event-participating-selector.component.ts
  libs/event/src/lib/selectors/map.component.ts
  libs/event/src/lib/services/event.service.ts
  libs/invitation/src/lib/invitation/invitation.component.html
  libs/invitation/src/lib/services/invitation.service.ts
  libs/models/src/lib/api/event.model.ts
Labels: enhancement
