Repository party-time-2/party-time, pull requests merged in 2023-05, with the labels that each got.

#59 improved html template
  apps/party-time-backend/src/main/resources/application.yml
  apps/party-time-backend/src/main/resources/mail/verify_account.mustache
Labels: bug

#55 F012 konto abmelden
  apps/party-time-frontend-e2e/src/e2e/logout.cy.ts
  apps/party-time-frontend-e2e/src/support/app.po.ts
  apps/party-time-frontend/src/app/app.component.ts
  apps/party-time-frontend/src/app/app.routes.ts
  docs/F012/F012_kontoAbmelden_act.plantuml
  docs/F012/F012_kontoAbmelden_seq.plantuml
  docs/PNG/F012/F012_kontoAbmelden_act.png
  docs/PNG/F012/F012_kontoAbmelden_seq.png
  docs/PNG/F012/Tests/party-time-change -- should show redirect_to_login.png
  libs/auth/README.md
  libs/auth/src/lib/+state/auth.state.ts
  libs/auth/src/lib/lib.routes.ts
  libs/auth/src/lib/logout/logout.component.ts
  libs/auth/src/lib/services/auth.service.ts
  libs/auth/src/lib/services/interceptor.service.ts
  libs/ui/src/lib/navbar/navbar.component.ts
Labels: documentation

#53 F015 konto löschen
  apps/party-time-backend/src/main/java/com/partytime/api/controller/AccountController.java
  apps/party-time-backend/src/main/java/com/partytime/api/dto/AccountDeleteDTO.java
  apps/party-time-backend/src/main/java/com/partytime/service/AccountDeletionService.java
  apps/party-time-backend/src/main/java/com/partytime/service/AccountService.java
  apps/party-time-frontend-e2e/src/support/app.po.ts
  apps/party-time-frontend/src/app/app.component.ts
  apps/party-time-frontend/src/app/app.routes.ts
  docs/F015/F015_kontoLoeschen_act.plantuml
  docs/F015/F015_kontoLoeschen_seq.plantuml
  docs/PNG/F015/F015_kontoLoeschen_act.png
  docs/PNG/F015/F015_kontoLoeschen_seq.png
  libs/account/.eslintrc.json
  libs/account/README.md
  libs/account/jest.config.ts
  libs/account/project.json
  libs/account/src/index.ts
  libs/account/src/lib/account/account.component.ts
  libs/account/src/lib/change/+state/change.state.ts
  libs/account/src/lib/change/change.component.html
  libs/account/src/lib/change/change.component.ts
  libs/account/src/lib/delete/+state/delete.state.ts
  libs/account/src/lib/delete/delete.component.html
  libs/account/src/lib/delete/delete.component.ts
  libs/account/src/lib/lib.routes.ts
  libs/account/src/lib/services/change.service.ts
  libs/account/src/lib/services/delete.service.ts
  libs/account/src/test-setup.ts
  libs/account/tsconfig.json
  libs/account/tsconfig.lib.json
  libs/account/tsconfig.spec.json
  libs/auth/src/lib/+state/auth.state.ts
  libs/auth/src/lib/services/interceptor.service.ts
  libs/change/src/index.ts
  libs/change/src/lib/lib.routes.ts
  tsconfig.base.json
Labels: enhancement

#60 Complete API for Milestone 2
  apps/party-time-backend/src/main/java/com/partytime/api/controller/AccountController.java
  apps/party-time-backend/src/main/java/com/partytime/api/controller/AuthController.java
  apps/party-time-backend/src/main/java/com/partytime/api/controller/EventController.java
  apps/party-time-backend/src/main/java/com/partytime/api/dto/account/AccountDTO.java
  apps/party-time-backend/src/main/java/com/partytime/api/dto/account/AccountDeleteDTO.java
  apps/party-time-backend/src/main/java/com/partytime/api/dto/account/AccountRegisterDTO.java
  apps/party-time-backend/src/main/java/com/partytime/api/dto/address/AddressDTO.java
  apps/party-time-backend/src/main/java/com/partytime/api/dto/event/EventCreateDTO.java
  apps/party-time-backend/src/main/java/com/partytime/api/dto/event/EventDTO.java
  apps/party-time-backend/src/main/java/com/partytime/api/dto/event/ParticipantDTO.java
  apps/party-time-backend/src/main/java/com/partytime/jpa/DatabaseConstants.java
  apps/party-time-backend/src/main/java/com/partytime/jpa/entity/Address.java
  apps/party-time-backend/src/main/java/com/partytime/jpa/mapper/AccountMapper.java
  apps/party-time-backend/src/main/java/com/partytime/service/AccountDeletionService.java
  apps/party-time-backend/src/main/java/com/partytime/service/AuthService.java
  apps/party-time-backend/src/test/java/com/partytime/api/controller/AuthControllerTest.java
  docs/ER-Modell/er-model.plantuml
  docs/PNG/ER-Modell/er-model.png
Labels: documentation
